// lib/demo-data.js — Jeu de démonstration statique
// Affiché uniquement si dma_dossiers est vide ou absent
// 4 dossiers couvrant les cas principaux de getNextAction

export const DEMO_DOSSIERS = [
  {
    id_dossier: 'DJ-2026-001',
    ref_devis: 'DEV-2026-001',
    nom_client: 'Famille Dupont',
    date_evenement: '2026-04-09',
    type_evenement: 'mariage',
    statut_commercial: 'confirme',
    statut_facturation: 'non_emise',
    statut_evenement: 'a_venir',
    total: 2800,
    acompte_attendu: 840,
    acompte_recu: 0,
    solde_attendu: 1960,
    solde_recu: 0,
    score_completude: 65,
    conducteur_ok: false,
    contact_jour_j: 'Sophie Dupont — 06 12 34 56 78',
    note: 'Salle Bellevue, 120 personnes',
    _meta: { date_creation: '2026-02-15', derniere_modification: '2026-03-10' },
  },
  {
    id_dossier: 'DJ-2026-002',
    ref_devis: 'DEV-2026-002',
    nom_client: 'Thomas Martin',
    date_evenement: '2026-04-20',
    type_evenement: 'anniversaire',
    statut_commercial: 'devis_envoye',
    statut_facturation: 'non_emise',
    statut_evenement: 'a_venir',
    total: 1200,
    acompte_attendu: 360,
    acompte_recu: 0,
    solde_attendu: 840,
    solde_recu: 0,
    score_completude: 0,
    conducteur_ok: false,
    contact_jour_j: '',
    note: '',
    _meta: { date_creation: '2026-03-10', derniere_modification: '2026-03-10' },
  },
  {
    id_dossier: 'DJ-2026-003',
    ref_devis: 'DEV-2026-003',
    nom_client: 'Claire Bernard',
    date_evenement: '2026-02-15',
    type_evenement: 'soiree_privee',
    statut_commercial: 'solde_recu',
    statut_facturation: 'soldee',
    statut_evenement: 'termine',
    total: 1800,
    acompte_attendu: 540,
    acompte_recu: 540,
    solde_attendu: 1260,
    solde_recu: 1260,
    score_completude: 100,
    conducteur_ok: true,
    contact_jour_j: 'Claire Bernard — 06 98 76 54 32',
    note: '',
    _meta: { date_creation: '2026-01-10', derniere_modification: '2026-02-16' },
  },
  {
    id_dossier: 'DJ-2026-004',
    ref_devis: 'DEV-2026-004',
    nom_client: 'ACME Corporate',
    date_evenement: '2026-05-10',
    type_evenement: 'seminaire',
    statut_commercial: 'devis_a_envoyer',
    statut_facturation: 'non_emise',
    statut_evenement: 'a_venir',
    total: 3500,
    acompte_attendu: 1050,
    acompte_recu: 0,
    solde_attendu: 2450,
    solde_recu: 0,
    score_completude: 0,
    conducteur_ok: false,
    contact_jour_j: '',
    note: 'Devis à finaliser — attente brief client',
    _meta: { date_creation: '2026-03-20', derniere_modification: '2026-03-20' },
  },
]
